name: anavandi_locator
description: "This project for finding the buses in a certain routes and shows the live location of the buses"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo_black.png
    - assets/logo/logo_white.png
